{
 "title": "Application Logs",
 "description": "Raw log streams from every environment (prod/staging)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production - Go App",
   "type": "logs",
   "description": "Displays all logs from the production container",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container=\"app-app-1\"}"
    }
   ]
  },
  {
   "title": "Production - Postgres Database",
   "type": "logs",
   "description": "Shows all logs from the production Postgres Database.",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{container=~\"app-db-1\"}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{container=\"app-nginx-1\"}"
    }
   ]
  },
  {
   "title": "Staging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Staging - Go App",
     "type": "logs",
     "description": "Shows all logs from the Staging Go App",
     "gridPos": { "h": 18, "w": 11, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{container=~\"app-db-1\"}"
      }
     ]
    },
    {
     "title": "Staging - Postgres Database",
     "type": "logs",
     "gridPos": { "h": 18, "w": 13, "x": 11, "y": 28 },
     "targets": [
      {
       "expr": "{container=\"postgres_staging_db\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Backup",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "{job=\"db-backup\"}"
      }
     ]
    },
    {
     "title": "Promtail",
     "type": "logs",
     "description": "Shows all the logs from the Promtail container on production VM",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "{container=\"promtail\"}"
      }
     ]
    }
   ]
  }
 ]
}