{
 "title": "Forgot password & reset password",
 "description": "Panels to describe, amount of reset and forgot password queries. Invalid tokens, Rate limiting, time series",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Log Stream forgot password",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"app-app-1\"} | json | event=\"auth.forgot_password\""
    }
   ]
  },
  {
   "title": " Log stream",
   "type": "logs",
   "description": "raw events",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"app-app-1\"} | json | event=\"auth.reset_password\""
    }
   ]
  },
  {
   "title": "Emails actually sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"forgot_password_sent\"[24h])"
    }
   ]
  },
  {
   "title": " Rate limited - forgot password",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"forgot_password_rate_limited\"[24h])"
    }
   ]
  },
  {
   "title": "Unknown email attempts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"forgot_password_unknown_email\"[24h])"
    }
   ]
  },
  {
   "title": "Total requests - forgot password",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"forgot_password_requested\"[24h])"
    }
   ]
  },
  {
   "title": "Success count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"reset_password_success\"[24h])"
    }
   ]
  },
  {
   "title": "Invalid token count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"reset_password_invalid_token\"[24h])"
    }
   ]
  },
  {
   "title": "Rate limited count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"reset_password_rate_limited\"[24h])"
    }
   ]
  },
  {
   "title": " Reset attempts count (stat panel, last 24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"app-app-1\"} | json | msg=\"reset_password_attempted\"[24h])"
    }
   ]
  },
  {
   "title": " Requests vs sent over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate({container=\"app-app-1\"} | json | msg=\"forgot_password_requested\"[$__interval]))"
    },
    {
     "expr": "sum(rate({container=\"app-app-1\"} | json | msg=\"forgot_password_sent\"[$__interval]))"
    }
   ]
  },
  {
   "title": " Success rate over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate({container=\"app-app-1\"} | json | msg=\"reset_password_success\"[$__interval]))\r\n/\r\nsum(rate({container=\"app-app-1\"} | json | msg=\"reset_password_attempted\"[$__interval]))"
    }
   ]
  }
 ]
}