{
 "title": "Infrastructure",
 "description": "Monitoring of cpu usage, memory, disc and so on\n",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Network recieved in bytes pr second",
   "type": "timeseries",
   "description": "How much network traffic is recieved on the machine in bytes pr second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmitted in bytes pr second",
   "type": "timeseries",
   "description": "how much each machine sends/transmits in bytes pr second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage in %",
   "type": "timeseries",
   "description": "How much of the hard drive is beng used on each machine",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"} * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage in %",
   "type": "timeseries",
   "description": "memory usage in % pr. instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage in %",
   "type": "timeseries",
   "description": "How much each instance uses the cpu",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load (1 min average)",
   "type": "timeseries",
   "description": "number of processes running on the cpu of a machine. 1 minutes avage (each machine has two cores)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "node_load1\r\n", "legendFormat": "__auto" }
   ]
  }
 ]
}