{
 "title": "Search SLO (Health)",
 "description": "Made to catch incidents fast with a dynamic range with default range to 1hr and a 5min window rate.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Search Success Rate (over time)",
   "type": "timeseries",
   "description": "Percentage of successful search requests over time, showing availability trends.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate({container=\"app-app-1\"} | json | path=\"/search\" and status=200 [5m]))\r\n/\r\nsum(rate({container=\"app-app-1\"} | json | path=\"/search\" [5m]))"
    }
   ]
  },
  {
   "title": "Search Endpoint Success Rate",
   "type": "stat",
   "description": "Percentage of successful /search page requests (HTTP 200) over total requests, indicating endpoint availability.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({container=\"app-app-1\"} |= \"\\\"path\\\":\\\"/search\\\"\" |= \"\\\"status\\\":200\"[5m]))\r\n/\r\nsum(rate({container=\"app-app-1\"} |= \"\\\"path\\\":\\\"/search\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "Search Error Rate",
   "type": "stat",
   "description": "Percentage of search events that result in errors over total search events",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({event=\"search\"} | json | level=\"ERROR\" [5m]))\r\n/\r\nsum(rate({event=\"search\"} | json [5m]))"
    }
   ]
  },
  {
   "title": "Search Events(5m)",
   "type": "timeseries",
   "description": "Number of search requests in the last 5 minutes, showing current traffic volume.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"app-app-1\"} | json | event=\"search\"[5m]))"
    }
   ]
  }
 ]
}