{
 "title": "User Activity (Realtime)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pageviews per Path (without assets/api)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path) (\r\n  count_over_time(\r\n    {container=\"app-app-1\"}\r\n    |= \"\\\"event\\\":\\\"pageview\\\"\"\r\n    | regexp \"\\\"path\\\":\\\"(?P<path>[^\\\"?]+)\"\r\n    != \"\\\"path\\\":\\\"/health\\\"\"\r\n    != \"\\\"path\\\":\\\"/logout\\\"\"\r\n    !~ \"\\\\.js\"\r\n    !~ \"\\\\.css\"\r\n    !~ \"\\\\.svg\"\r\n    !~ \"/static/\"\r\n    !~ \"/api/\"\r\n    [$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Active Users (5 min)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum by (tracking_id) (\r\n    count_over_time(\r\n      {container=\"app-app-1\"}\r\n      | json\r\n      | event=\"pageview\"\r\n      | tracking_id != \"\"\r\n    [5m])\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Search Success Rate ",
   "type": "stat",
   "description": "Shows the percentage of search queries that returned results.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  count_over_time(\r\n    {container=\"app-app-1\"}\r\n    | json\r\n    | event=\"search\"\r\n    | query !~ \"^.{0,2}$\"\r\n    | results > 0\r\n  [5m])\r\n)\r\n/\r\nsum(\r\n  count_over_time(\r\n    {container=\"app-app-1\"}\r\n    | json\r\n    | event=\"search\"\r\n    | query !~ \"^.{0,2}$\"\r\n  [5m])\r\n)"
    }
   ]
  },
  {
   "title": "Search success rate ",
   "type": "timeseries",
   "description": "Shows the percentage of search queries that return results, filtered to include only meaningful queries. Is calculated by an average for every hour.",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(\r\n  count_over_time(\r\n    {container=\"app-app-1\"}\r\n    | json\r\n    | event=\"search\"\r\n    | query != \"\"\r\n    | results > 0\r\n  [$__range])\r\n)\r\n/\r\nsum(\r\n  count_over_time(\r\n    {container=\"app-app-1\"}\r\n    | json\r\n    | event=\"search\"\r\n    | query != \"\"\r\n  [$__range])\r\n)"
    }
   ]
  }
 ]
}