---
- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Ensure docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Ensure cli-plugins directory exists
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'
  become: yes

- name: Install Docker Compose v2 plugin (manual)
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'
  become: yes

- name: Reset SSH connection to apply group membership
  ansible.builtin.meta: reset_connection