---
- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Ensure docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Add azureuser to docker group
  ansible.builtin.user:
    name: azureuser
    groups: docker
    append: yes

- name: Reset SSH connection to apply group membership
  ansible.builtin.meta: reset_connection