global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['10.0.2.5:9100']
        labels:
          env: prod
          instance: knowledge
      - targets: ['10.0.2.4:9100']
        labels:
          env: prod
          instance: kmonitor