global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets:
          - 'knowledge-private-ip:9100'
          - 'kmonitor-private-ip:9100'
        labels:
          env: prod