FROM node:20-alpine

WORKDIR /app

COPY db-migrations/package*.json db-migrations/
RUN npm install --prefix db-migrations

COPY db-migrations db-migrations

WORKDIR /app/db-migrations

CMD ["npx", "knex", "--help"]
