services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: knowledge
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: knowledgeable
    ports:
      - "8080:8080"
    working_dir: /workspace
    volumes:
      - .:/workspace

    environment:
      APP_ENV: dev
      DATABASE_URL: postgres://user:password@db:5432/knowledge?sslmode=disable
    depends_on:
      - db

  frontend:
    image: node:20
    working_dir: /workspace
    volumes:
      - .:/workspace 
    command: sh -c "npm install --prefix frontend && npm run dev --prefix frontend"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true

volumes:
  postgres_data: