FROM golang:1.24-alpine

WORKDIR /workspace

RUN apk add --no-cache git

RUN go install github.com/cosmtrek/air@v1.52.0

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", "frontend/.air.toml"]