FROM golang:1.24-alpine AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o server ./cmd/server


FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=build /app/server /app/server
COPY --from=build /app/knowledge.sql /app/knowledge.sql
COPY --from=build /app/templates /app/templates
COPY --from=build /app/static /app/static

ENTRYPOINT ["/app/server"]