name: CD - Staging Deployment

on:
  workflow_run:
    workflows: [ "CD - Delivery" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key

      - name: Deploy staging
        run: |
         ssh -i ~/.ssh/ssh_key -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            set -e

            echo "[DEPLOY] Starting staging deploy"

            echo "[DEPLOY] Logging into registry"
            echo "${{ secrets.CR__PAT }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            echo "[DEPLOY] Moving to app directory"
            cd ~/app

            echo "[DEPLOY] Pulling images"
            docker compose -p staging -f docker-compose-staging.yml pull

            echo "[DEPLOY] Running migrations"
            docker compose -p staging -f docker-compose-staging.yml --profile tools run --rm migrations \
              sh -c "
                echo '[MIGRATION] Running migrations...'
                until npx knex migrate:latest; do
                  echo '[MIGRATION] Retrying...'
                  sleep 3
                done
              "

            echo "[DEPLOY] Starting services"
            docker compose -p staging -f docker-compose-staging.yml up -d

            echo "[DEPLOY] Checking containers"
            docker compose -p staging ps

            echo "[DEPLOY] Staging deploy completed"
            EOF