name: CD - Deployment

on:
  workflow_run:
    workflows: [ "CD - Delivery" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Add SSH key to runner
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key

      - name: Transfer docker-compose-prod.yml to server
        run: |
          scp -i ~/.ssh/ssh_key -o StrictHostKeyChecking=no \
            knowledgeable/docker-compose-prod.yml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/app/docker-compose.yml

      - name: Write remote production .env
        run: |
          ssh -i ~/.ssh/ssh_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > ~/app/.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ~/app/.env
            echo "POSTGRES_DB=knowledge" >> ~/app/.env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ~/app/.env
            echo "APP_DOMAIN=www.knowledgeable.one" >> ~/app/.env
          EOF
      - name: Deploy on server
        run: |
          ssh -i ~/.ssh/ssh_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            echo "${{ secrets.CR__PAT }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            cd ~/app
            docker compose pull app db migrations
            docker compose down
            docker compose up -d db app nginx
            timeout 60 bash -c "until docker compose exec -T db pg_isready -U user; do sleep 2; done"
            docker compose run --rm migrations npx knex migrate:latest
          EOF