name: Security scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPRIVATE: github.com/knowledgeables/*
      GITHUB_AUTHENTICATION_TOKEN: ${{ secrets.CR__PAT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: false

      - name: Download dependencies
        working-directory: knowledgeable
        run: go mod download

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./knowledgeable/...'


      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif

      - name: Save SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gosec-results
          path: results.sarif